### ISSUE TITLE
Tooltips are unreadable

### ISSUE THREAD

**Issue by rumangerst** [scionicspectre/BreezyGTK#1]
It seems that GTK won't use a dark tooltip background color (for me at least)

See following article, which shows the problem: http://www.iwillfolo.com/how-to-change-gtk-apps-tooltips-text-and-background-color/
If I edit the tooltip colors like mentioned on this article, I can read the tooltips

Kubuntu 15.04, Plasma 5.3 from backports

**Comment by scionicspectre** [comment]
Thanks for bringing this to my attention. I made it more readable and subsequently added transparency and rounded corners. I'll still have to check Breeze for more accurate colors, but for now I'd say this is resolved.
